name: Auto Merge Feature Branch

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request to Development
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: development
          branch: ${{ github.ref }}
          title: 'feat: Merge feature branch into development'
          body: 'This PR merges the feature branch into the development branch.'

  merge-to-development:
    runs-on: ubuntu-latest
    needs: create-pull-request
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            const pr_number = context.payload.pull_request.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'squash'
            });

  merge-development-to-main:
    runs-on: ubuntu-latest
    needs: merge-to-development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge Development to Main
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout main
          git merge development
          git push origin main
